#!/bin/sh -e

. "$(dirname "$0")/config"

TARGET="${1:-all}"
COMPILER_TARGET="$TARGET"
CPP_STANDARD_ARGS=

if [ "$TARGET" = all ]; then
    OUTPUT_DIR="$FORMATS_COMPILED_DIR"
else
    OUTPUT_DIR="$FORMATS_COMPILED_DIR/$TARGET"
fi

if [ "$TARGET" = cpp_stl_11 ]; then
    COMPILER_TARGET=cpp_stl
    CPP_STANDARD_ARGS="--cpp-standard 11"
fi

if [ "$TARGET" = cpp_stl_98 ]; then
    COMPILER_TARGET=cpp_stl
    CPP_STANDARD_ARGS="--cpp-standard 98"
fi

rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# 	--java-from-file-class io.kaitai.struct.RandomAccessFileKaitaiStream \

"$COMPILER_DIR/jvm/target/universal/stage/bin/kaitai-struct-compiler" -- \
	--verbose file -t "$COMPILER_TARGET" $CPP_STANDARD_ARGS -d "$OUTPUT_DIR" \
	--import-path "$FORMATS_REPO_DIR" \
	--import-path "$FORMATS_KSY_DIR/ks_path" \
	--java-package io.kaitai.struct.testformats \
	--php-namespace 'Kaitai\Struct\Tests' \
	--python-package testformats \
	--go-package test_formats \
	--nim-module "kaitai_struct_nim_runtime" \
	--nim-opaque "../../tests/spec/nim/opaque/" \
	"$FORMATS_KSY_DIR"/*.ksy || :

if [ "$TARGET" = java ] || [ "$TARGET" = all ]; then
	"$COMPILER_DIR/jvm/target/universal/stage/bin/kaitai-struct-compiler" -- \
		--verbose file -t java -d "$FORMATS_COMPILED_DIR/java/src" \
		--no-auto-read \
		--read-write \
		--import-path "$FORMATS_REPO_DIR" \
		--import-path "$FORMATS_KSY_DIR/ks_path" \
		--java-package io.kaitai.struct.testwrite \
		"$FORMATS_KSY_DIR"/*.ksy || :
fi

if [ "$TARGET" = python ] || [ "$TARGET" = all ]; then
	mv -n "$FORMATS_COMPILED_DIR/python" "$FORMATS_COMPILED_DIR/python-tmp"
	mkdir "$FORMATS_COMPILED_DIR/python"
	mv -n "$FORMATS_COMPILED_DIR/python-tmp" "$FORMATS_COMPILED_DIR/python/testformats"
	# Although Python 3 doesn't require empty `__init__.py` files, omitting them will create
	# a [namespace package](https://docs.python.org/3/glossary.html#term-namespace-package).
	# This is a relatively advanced feature and is recommended to be avoided unless needed.
	touch "$FORMATS_COMPILED_DIR/python/testformats/__init__.py"

	"$COMPILER_DIR/jvm/target/universal/stage/bin/kaitai-struct-compiler" -- \
		--verbose file -t python -d "$FORMATS_COMPILED_DIR/python/testwrite" \
		--no-auto-read \
		--read-write \
		--import-path "$FORMATS_REPO_DIR" \
		--import-path "$FORMATS_KSY_DIR/ks_path" \
		--python-package testwrite \
		"$FORMATS_KSY_DIR"/*.ksy || :

	# See the comment above about why we are creating this empty `__init__.py` file.
	touch "$FORMATS_COMPILED_DIR/python/testwrite/__init__.py"
fi

if [ "$TARGET" = cpp_stl_11 ] || [ "$TARGET" = all ]; then
	rm -rf "$FORMATS_COMPILED_DIR/cpp_stl_11_write"
	mkdir -p "$FORMATS_COMPILED_DIR/cpp_stl_11_write"

	"$COMPILER_DIR/jvm/target/universal/stage/bin/kaitai-struct-compiler" -- \
		--verbose file -t cpp_stl --cpp-standard 11 -d "$FORMATS_COMPILED_DIR/cpp_stl_11_write" \
		--no-auto-read \
		--read-write \
		--import-path "$FORMATS_REPO_DIR" \
		--import-path "$FORMATS_KSY_DIR/ks_path" \
		"$FORMATS_KSY_DIR"_rw/hello_world_write.ksy || :
fi
